import re
import torch
from transformers import AutoModelForSequenceClassification, AutoTokenizer


class KoalaModerationFilter:
    """
    Content moderation filter using the KoalaAI/Text-Moderation sequence classification model.

    The model detects categories of inappropriate content including:
    - S: Sexual content
    - H: Hate speech
    - V: Violence
    - HR: Harassment
    - SH: Self-harm
    - S3: Sexual content involving minors
    - H2: Threatening hate speech
    - V2: Graphic violence
    - OK: Not offensive (safe content)
    """

    def __init__(self, device: str = "cpu") -> None:
        """
        Initialize the moderation filter by loading the pretrained model and tokenizer,
        and moving the model to the specified device.

        Args:
            device (str): Device to run the model on, e.g., "cpu", "cuda", or "mps".
        """
        # Load the model and tokenizer from Hugging Face
        self.model = AutoModelForSequenceClassification.from_pretrained(
            "KoalaAI/Text-Moderation"
        )
        self.tokenizer = AutoTokenizer.from_pretrained("KoalaAI/Text-Moderation")

        # Move model to the specified device (e.g., "cuda" for GPU)
        self.device = device
        self.model.to(self.device)
        self.model.eval()

    def check(self, text: str, threshold: float = 0.5) -> bool:
        """
        Evaluate the input text for flagged content based on model prediction.

        Args:
            text (str): Input text string to be moderated.
            threshold (float): Probability threshold above which content is considered flagged.

        Returns:
            bool: True if content is flagged (inappropriate), False otherwise.
        """
        # Tokenize the input and run it through the model
        inputs = self.tokenizer(text, return_tensors="pt").to(self.device)
        with torch.no_grad():
            outputs = self.model(**inputs)

        # Get probabilities using softmax
        probabilities = outputs.logits.softmax(dim=-1).squeeze()

        # Get the label with the highest probability
        top_prob, top_idx = torch.max(probabilities, dim=0)
        top_label = self.model.config.id2label[top_idx.item()]

        if top_label != "OK" and top_prob.item() > threshold:
            return True
        return False


async def generate_domain_suggestions(
    model: torch.nn.Module, tokenizer: AutoTokenizer, device: str, description: str
) -> str:
    """
    Generate domain name suggestions given a textual description using a language model.

    Args:
        model (torch.nn.Module): The language generation model.
        tokenizer (AutoTokenizer): Tokenizer corresponding to the model.
        device (str): Device on which to perform inference.
        description (str): Text description to base suggestions on.

    Returns:
        str: Raw text output from the model containing domain suggestions.
    """

    prompt = (
        "Suggest domain names from the description:\n"
        "Output each example as a single line JSON object (JSON Lines format), with keys:\n"
        '  - "domain": the domain string\n'
        '  - "confidence": a float from 0.00–1.00.\n\n'
        "### Description:\n"
        f"{description}\n\n"
        "### Response:\n"
    )

    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=250,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
            do_sample=True,
            temperature=0.6,
            top_p=0.9,
        )

    response_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    generated_part = response_text.split("### Response:\n")[-1].strip()

    return generated_part


def clean_raw_response(raw_response: str) -> str:
    """
    Clean the raw text response by removing unwanted tokens or markers.

    Args:
        raw_response (str): The raw text generated by the model.

    Returns:
        str: The cleaned response string.
    """
    cleaned = re.sub(r"<Response>\s*|\s*<\|endoftext\|>$", "", raw_response.strip())
    cleaned = cleaned.rstrip("|").strip()
    return cleaned


def get_device() -> str:
    """
    Detect the best available device for PyTorch computations.

    Checks for CUDA-enabled GPUs, Apple Silicon MPS backend, and defaults to CPU.

    Returns:
        str: The device string identifier ("cuda", "mps", or "cpu").
    """
    if torch.cuda.is_available():
        return "cuda"
    elif torch.backends.mps.is_available():
        return "mps"
    else:
        return "cpu"
